"""add shipping_rate_id to orders

Revision ID: 61aae706fb85
Revises: 
Create Date: 2025-09-10 19:08:53.691615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61aae706fb85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_rate_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_rate_id')
    op.drop_column('orders', 'shipping_method')
    # ### end Alembic commands ###
